baseURL = 'https://juegosaccesibles.oriolgomez.com/'
languageCode = 'es-es'
title = 'Juegos Accesibles'
defaultContentLanguage = 'es'
defaultContentLanguageInSubdir = false
disableDefaultLanguageRedirect = false
disableLanguages = []
[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

[languages]
  [languages.es]
    disabled = false
    languageCode = 'es'
    languageDirection = 'ltr'
    languageName = 'es'
    title = 'Juegos Accesibles'
    weight = 0

[taxonomies]
  platform = "platforms"
  language = "languages"
  genre = "genres"

  [[menu.main]]
  name = "Inicio"
    weight = 1
    url = "/"

    [[menu.main]]
    name = "Juegos en español"
    weight = 2
    url = "/languages/español/"

    [[menu.main]]
    name = "Juegos para Windows"
    weight = 4
    url = "/platforms/windows/"
    [[menu.main]]
    name = "Juegos para iOS"
    weight = 5
    url = "/platforms/ios/"
    [[menu.main]]
    name = "Juegos para Android"
    weight = 6
    url = "/platforms/android/"

    [[menu.main]]
    name = "Juegos para Mac"
    weight = 7
    url = "/platforms/mac/"

